# Description: This file is responsible for deploying the application in the Kubernetes cluster.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tech-challenge
  namespace: core
  labels:
    app: tech-challenge
spec:
    replicas: 2
    selector:
      matchLabels:
        app: tech-challenge
    strategy:
        type: RollingUpdate
        rollingUpdate:
            maxSurge: 1
            maxUnavailable: 1
    template:
        metadata:
            labels:
                app: tech-challenge
        spec:
            containers:
                -   name: tech-challenge
                    image: fwcpereira/tech-challenge:v3.0.0
                    imagePullPolicy: Always
                    ports:
                        -   containerPort: 3000
                    envFrom:
                        - configMapRef:
                            name: tech-challenge
                        - secretRef:
                            name: tech-challenge
                    livenessProbe:
                        httpGet:
                          path: /heathlz
                          port: 3000
                        initialDelaySeconds: 10
                        failureThreshold: 3
                        periodSeconds: 10
                        successThreshold: 1
                        timeoutSeconds: 5
                    readinessProbe:
                        httpGet:
                            path: /heathlz
                            port: 3000
                        initialDelaySeconds: 10
                        failureThreshold: 3
                        periodSeconds: 10
                        successThreshold: 1
                        timeoutSeconds: 1
                    startupProbe:
                        exec:
                            command:
                                - /bin/sh
                                - -c
                                - node -v
                        initialDelaySeconds: 5
                        successThreshold: 1
                        timeoutSeconds: 1
                    resources:
                        requests:
                            memory: "550Mi"
                            cpu: "500m"
                        limits:
                            memory: "650Mi"
                            cpu: "700m"
            restartPolicy: Always
            terminationGracePeriodSeconds: 30
            serviceAccountName: tech-service-account
