# Description: This file is used to create a service for the tech-challenge application.
apiVersion: v1
kind: Service
metadata:
  name: tech-challenge
  namespace: core
  labels:
    app: tech-challenge
spec:
    selector:
        app: tech-challenge
    ports:
        -   protocol: TCP
            port: 3000
            targetPort: 3000
    type: ClusterIP
