# Description: Horizontal Pod Autoscaler for tech-challenge deployment.
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: tech-challenge
  namespace: core
spec:
    scaleTargetRef:
      apiVersion: apps/v1
      kind: Deployment
      name: tech-challenge
    minReplicas: 1
    maxReplicas: 6
    targetCPUUtilizationPercentage: 45


