# Description: This file is responsible for creating a RoleBinding in the Kubernetes cluster.
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
    name: tech-role-binding
    namespace: core
subjects:
    - kind: ServiceAccount
      name: tech-service-account
      namespace: core
roleRef:
    kind: Role
    name: tech-role
    apiGroup: rbac.authorization.k8s.io
