services:
    node-app:
        build:
            context: .
            dockerfile: ./docker/Dockerfile_node
        container_name: node-app
        hostname: node-app
        restart: always
        networks:
            - tech-network
        env_file:
            - .env
        tty: true
        ports:
            - "3000:3000"
        depends_on:
            postgres-db:
                condition: service_healthy

    postgres-db:
        image: postgres:alpine
        container_name: postgres-db
        hostname: postgres-db
        restart: always
        networks:
            - tech-network
        env_file:
            - .env
        tty: true
        ports:
            - "5432:5432"
        volumes:
            - ./postgresql_data:/var/lib/postgresql/data
        healthcheck:
            test: ["CMD-SHELL", "pg_isready"]
            interval: 10s
            timeout: 5s
            retries: 5

networks:
    tech-network:
        driver: bridge

volumes:
    postgresql_data:
