# Description: ConfigMap for PostgreSQL configuration file pg_hba.conf.
apiVersion: v1
kind: ConfigMap
metadata:
    name: postgresql-config
    namespace: tool-database
    labels:
        app: postgresql
data:
    pg_hba.conf: |
        # PostgreSQL Client Authentication Configuration File
        # ===================================================
        # Refer to the "Client Authentication" section in the
        # PostgreSQL documentation for a complete description
        # of this file.  A short synopsis follows.
        #
        # This file controls: which hosts are allowed to connect,
        # how clients are authenticated, which PostgreSQL user names
        # they can use, which databases they can access.  Records
        # take one of these forms:
        #
        # local      DATABASE  USER  METHOD  [OPTIONS]
        # host       DATABASE  USER  ADDRESS  METHOD  [OPTIONS]
        # hostssl    DATABASE  USER  ADDRESS  METHOD  [OPTIONS]
        # hostnossl  DATABASE  USER  ADDRESS  METHOD  [OPTIONS]
        #
        # The first field is the connection type: "local" is a Unix-domain
        # socket, "host" is either a plain or SSL-encrypted TCP/IP socket,
        # "hostssl" is an SSL-encrypted TCP/IP socket, and "hostnossl"
        # is a plain TCP/IP socket.
        #
        # METHOD can be "trust", "reject", "md5", "password", "gss", "sspi",
        # "krb5", "ident", "peer", "pam", "ldap", "radius" or "cert".
        # Note that "password" sends passwords in clear text; "md5" is
        # preferred since it sends encrypted passwords.
        #
        # OPTIONS are a set of options for the authentication in the format
        # NAME=VALUE.  The available options depend on the different
        # authentication methods -- refer to the "Client Authentication"
        # section in the documentation for details.
        #
        # Database and user names containing spaces, commas, quotes and other
        # special characters must be quoted.  Quoting one of the keywords
        # "all", "sameuser", "samerole" or "replication" makes the name lose
        # its special character, and just match a database or username with
        # that name.
        #
        # This file is read on server startup and when the server receives
        # a SIGHUP signal.  If you edit the file on a running system, you have
        # to SIGHUP the server for the changes to take effect.  You can use
        # "pg_ctl reload" or "kill -HUP `cat /var/lib/postgresql/data/postmaster.pid`"
        # to force a reload.  You can also run "SELECT pg_reload_conf()".

        # Put your actual configuration here
        # Allow connections from any IP address
        host    all             all             0.0.0.0/0               md5
        host    tech_challenge  postgresql      10.1.1.70/32            md5
