# Description: Secret for PostgreSQL.
apiVersion: v1
kind: Secret
metadata:
    name: postgresql-secret
    namespace: tool-database
    labels:
        app: postgresql
type: Opaque
data:
    POSTGRES_USER: cG9zdGdyZXNxbA==
    POSTGRES_PASSWORD: cG9zdGdyZXNxbA==
    POSTGRES_ROOT_USER: dGVjaF9jaGFsbGVuZ2U=
    POSTGRES_ROOT_PASSWORD: MTIzMzQ0cmV3b2tva29jZjQ1Nm9wb2twazV0NDU=
